### ISSUE TITLE
build in support for 3.4 and dbr 12.2 and 13.x starter

### ISSUE THREAD

**Issue by chris-twiner** [sparkutils/quality#5]
12.2 merges https://issues.apache.org/jira/browse/SPARK-41049 into its 3.3.2 base removing Stateful.

3.4 also changes bind in hofs, compilation handling, type checking and error message format (change between rc1 and rc4).

Frameless no longer works with the build.

Another compat layer needed.

**Comment by chris-twiner** [comment]
frameless issue

```
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.ScalaReflection$.dataTypeFor(Lscala/reflect/api/TypeTags$TypeTag;)Lorg/apache/spark/sql/types/DataType;

	at frameless.TypedEncoder$$anon$19.toCatalyst(TypedEncoder.scala:453)
	at frameless.RecordEncoder.$anonfun$toCatalyst$2(RecordEncoder.scala:155)
```

**Comment by chris-twiner** [comment]
1785768 seems to work for 12.2 lts - only failed on verifyInputParams - so possibly old 340 syntax is being used.

**Comment by chris-twiner** [comment]
Raised typelevel/frameless#689 for the frameless fix

**Comment by chris-twiner** [comment]
per typelevel/frameless#701 integrating with Spark Connect is probably impossible.  Moreover the only expressions allowed in columns are [those defined here](https://github.com/apache/spark/blob/cabba33cb277c5c81c2b12b83fcfd19c496d5b50/connector/connect/common/src/main/protobuf/spark/connect/expressions.proto).  So there is no way to inject dq rules or functions through connect either - a bit of dead functionality.

**Comment by chris-twiner** [comment]
dcb4ba1 uses normal 3.4

**Comment by chris-twiner** [comment]
as 13.0 dbr is out this should also be tested against.  Running 12.2 dbr against it only had the frameless failure (dataTypeFor).  As such no special build will be created.

**Comment by chris-twiner** [comment]
213 failures on 13.1 beta on latest snapshot (vs. the 1 on all other dbrs including 13.0)

**Comment by chris-twiner** [comment]
scalatest was it, can't now run individual tests but only 8 fail on 13.1 (7 new):

BaseFunctionalityTest
testComparableResults - all comparable_maps tests fail due to:
NoSuchMethodErrror org.apache.spark.sql.types.AtomicType.ordering: scala.math.Ordering

so a signature change not present on 13.0.  Probably the same for the ValidationTests as well

ValidationTest
testFunctionSyntaxError is broken: 219
testOutputFunctionSyntaxError: 214

**Comment by chris-twiner** [comment]
[43019](https://issues.apache.org/jira/browse/SPARK-43019?jql=project%20%3D%20SPARK%20AND%20text%20~%20ordering%20ORDER%20BY%20key%20DESC) is the reason for the ordering issue.  13.1 backports it (also declared in the release notes)

**Comment by chris-twiner** [comment]
3.4 done, 12.2 all tests working, 13.1 as well
